### ISSUE TITLE
Reconnect doesn't return home

### ISSUE THREAD

**Issue by richard-pianka** [KnightsOfGlory/WarChat#79]

**Comment by BinaryNinjas** [comment]
On Mac - reconnect appears to send back to home channel but is inconsistent.  Ends up in channel "Chat" on occasion.

**Comment by richard-pianka** [comment]
Also occurs on totally fresh run:

`Exited program - restarted it - connected - went to channel chat instead of home channel`

**Comment by richard-pianka** [comment]
https://github.com/fjaros/init6/blob/d0df994de59da4e028c42fa17c0bb33fc84b9cd4/src/main/scala/com/init6/users/UserActor.scala#L490
